apiVersion: batch/v1
kind: Job
metadata:
  name: django-static-job
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: django-static
          image: victorysokolov/django-blog:89a365019c6c0124f41240ae956f7d7b56b29859
          imagePullPolicy: Always
          command: ['/bin/sh', '-c']
          args:
            - python manage.py collectstatic --noinput
          # env:
          #   - name: GOOGLE_APPLICATION_CREDENTIALS
          #     value: /secrets/key.json
          envFrom:
            - secretRef:
                name: djapp
          volumeMounts:
            # - name: google-credentials-volume
            #   mountPath: /secrets
            #   readOnly: true
            - name: static-storage
              mountPath: /app/output/static/
      volumes:
        # - name: google-credentials-volume
        #   secret:
        #     secretName: google-credentials
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-storage-pvc
      restartPolicy: Never
  backoffLimit: 1
