# Generated by Django 3.2.9 on 2022-03-05 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(max_length=100, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(default=uuid.uuid4),
        ),
    ]
