# Generated by Django 5.2.4 on 2025-08-09 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_post_content_alter_post_slug_alter_post_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_title_4d5512_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title', 'created_at'], name='posts_title_e2b093_idx'),
        ),
    ]
