apiVersion: batch/v1
kind: Job
metadata:
  name: django-static-job
spec:
  template:
    spec:
      containers:
        - name: django-static
          image: victorysokolov/django-blog:5a2fadd5cefdac9791935cc1c89dd5a3e18c4cb9
          imagePullPolicy: Always
          command: ['/bin/sh', '-c']
          args:
            - python manage.py collectstatic --noinput && python manage.py compress --force
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/key.json
          envFrom:
            - secretRef:
                name: djapp
          volumeMounts:
            - name: google-credentials-volume
              mountPath: /secrets
              readOnly: true
            - name: static-storage
              mountPath: /app/output/static/
      volumes:
        - name: google-credentials-volume
          secret:
            secretName: google-credentials
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-storage-pvc
      restartPolicy: Never
  backoffLimit: 1
