apiVersion: batch/v1
kind: Job
metadata:
  name: django-static-job
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: django-static
          image: victorysokolov/django-blog:d5efd7260595bca0b468a0e1a65b33800ba3f3b9
          imagePullPolicy: Always
          command: ['/bin/sh', '-c']
          args:
            - python manage.py collectstatic --noinput
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/key.json
          envFrom:
            - secretRef:
                name: djapp
          volumeMounts:
            - name: google-credentials-volume
              mountPath: /secrets
              readOnly: true
            - name: static-storage
              mountPath: /app/output/static/
      volumes:
        - name: google-credentials-volume
          secret:
            secretName: google-credentials
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-storage-pvc
      restartPolicy: Never
  backoffLimit: 1
