repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(.)+\.(json|yaml)$
      - id: debug-statements
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'
    hooks:
      - id: mypy
        additional_dependencies: [
          'djangorestframework-stubs',
          'django-stubs',
        ]

  - repo: local
    hooks:
      - id: check-django-migrations
        name: Check django migrations
        entry: poetry run python manage.py makemigrations --dry-run --check
        language: system
        types: [python] # hook only runs if a python file is staged
        pass_filenames: false

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args: ['--create', "--track", "--python-folders", "tests,somefolder,otherfolder"]
