repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(.)+\.(json|yaml)$
      - id: debug-statements
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v1.8.0'
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [
  #         'djangorestframework-stubs',
  #         'django-stubs',
  #       ]

  - repo: local
    hooks:
      - id: check-django-migrations
        name: Check django migrations
        entry: uv run python manage.py makemigrations --dry-run --check
        language: system
        types: [python] # hook only runs if a python file is staged
        pass_filenames: false

  - repo: local
    hooks:
      - id: check-django
        name: Run Check command for Django
        entry: uv run python manage.py check --settings=djangoblog.settings --deploy
        language: system
        types: [python] # hook only runs if a python file is staged
        pass_filenames: false

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.30.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args:
          [
            '--create',
            '--track',
            '--python-folders',
            'tests,somefolder,otherfolder',
          ]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.22.1'
    hooks:
      - id: django-upgrade
        args: [--target-version, '5.0']

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        args:
          - --config-file=.yamllint.yaml

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: '1.3.2'
    hooks:
      - id: djade
        args: [--target-version, '5.0']

  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: uv run python bandit djangoblog/
        language: python
        language_version: python3
        types: [python]
        require_serial: true
