services:

  dj-app:
    container_name: dj-app
    env_file:
      - .env.prod
    build:
      context: .
    volumes:
      - static_volume:/app/output/static
    networks:
      - default
    ports:
      - 8001:80
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'

  celery_worker:
    restart: on-failure
    container_name: dj-celery-worker
    build:
      context: .
    env_file:
      - .env.prod
    command:
      sh -c "DJANGO_ENV=production celery -A djangoblog worker -l info --uid=nobody --gid=nogroup"
    healthcheck:
      test: ["CMD-SHELL", "celery", "-A", "djangoblog", "inspect", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5
    depends_on:
      - dj-app
      - redis
      - postgres
      - nginx
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'

  redis:
    container_name: dj-redis
    restart: unless-stopped
    build:
      context: docker/redis
    environment:
      - TZ=Etc/GMT-3
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    # Run as privileged to allow the container to change the
    # vm.overcommit_memory setting
    privileged: true
    volumes:
      - djredis:/data:rw
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'

  nginx:
    restart: on-failure
    container_name: dj-nginx
    build:
      context: docker/nginx/
    networks:
      - default
    volumes:
      - static_volume:/app/output/static
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      timeout: 25s
      retries: 5
    depends_on:
      - dj-app
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'

  postgres:
    container_name: dj-postgres
    restart: on-failure
    networks:
      - default
    env_file:
      - .env
    build:
      context: docker/postgres/
    ports:
      - "5431:5431"
    volumes:
      - djdata:/var/lib/postgresql/data
    environment:
      - TZ=Etc/GMT-3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${PGPORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'

  haproxy:
    container_name: dj-haproxy
    networks:
      - default
    build:
      context: docker/haproxy/
    restart: always
    ports:
      - "80:80"
    depends_on:
      - dj-app

networks:
  default:
    driver: bridge

volumes:
  djdata:
  djredis:
  static_volume:
