name: djangoblog

services:

  # Docker logs monitoring
  dozzle:
    # Disable service
    profiles:
      - donotstart
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8889:8889

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - default
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/infra/prometheus

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - prometheus
    ports:
      - 3010:3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3010/api/health && echo 'ready'"]
      interval: 10s
      retries: 30
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_LOG_LEVEL: debug
      GF_LOG_FILTERS: "rendering:debug"
      RENDERING_MODE: "reusable"
      ENABLE_METRICS: true
    volumes:
      - ./infra/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana

  rabbitmq:
    image: rabbitmq:3.11.26-management
    profiles:
      - donotstart
    platform: linux/arm64
    security_opt:
      - no-new-privileges:true
    ports:
      - 5675:5675
    develop:
      watch:
        - action: rebuild
          path: ./infra/prometheus/

  statsd-exporter:
    image: prom/statsd-exporter
    networks:
      - default
    ports:
      - "9125:9125/udp"
      - "9102:9102"


networks:
  default:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
  rabbitmq_data:
