services:
  django:
    build:
      context: .
      dockerfile: ./docker/debugpy/Dockerfile
    command: ["sh", "-c", "python -m debugpy --listen 0.0.0.0:5678"]
    ports:
      - 80:80
      - 5678:5678
