services:

  dj-app:
    container_name: dj-app
    env_file:
      - .env.prod
    build:
      context: .
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    ports:
      - 1337:80
    depends_on:
      - postgres
      - nginx
      - redis

  celery_worker:
    restart: on-failure
    container_name: dj-celery-worker
    build:
      context: .
    env_file:
      - .env.prod
    command: sh -c "DJANGO_ENV=production celery -A djangoblog worker -l info --uid=nobody --gid=nogroup"
    healthcheck:
      test: ["CMD-SHELL", "celery", "-A", "djangoblog", "inspect", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5
    security_opt:
      - no-new-privileges:true
    depends_on:
      - dj-app
      - redis
      - postgres


  redis:
    container_name: dj-redis
    restart: on-failure
    build:
      context: docker/redis
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Etc/GMT-3
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    # Run as privileged to allow the container to change the vm.overcommit_memory setting
    privileged: true
    volumes:
      - ./data/redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  nginx:
    restart: on-failure
    container_name: dj-nginx
    build:
      context: docker/nginx/
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    ports:
      - "8080:80"

  postgres:
    container_name: dj-postgres
    restart: on-failure
    networks:
      - default
    env_file:
      - .env
    build:
      context: docker/postgres/
    security_opt:
      - no-new-privileges:true
    ports:
      - "5431:5431"
    volumes:
      - djdata:/var/lib/postgresql/data
    environment:
      - TZ=Etc/GMT-3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${PGPORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3


networks:
  default:
    driver: bridge

volumes:
  djdata:
