name: djangoblog

x-environment: &default-env
  TZ: Europe/Riga

services:

  app:
    extends:
      file: ./docker/docker-compose.common.yml
      service: application
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
    networks:
      - default
      - docker-elk_elk
    volumes:
       - static_volume:/app/output/static
    ports:
      - 8001:8001
    expose:
      - 8001
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:80/healthcheck"]
      interval: 15s
      timeout: 12s
      retries: 5
      start_period: 60s

  worker:
    extends:
      file: ./docker/docker-compose.common.yml
      service: application
    restart: unless-stopped
    environment:
      <<: *default-env
    networks:
      - default
      - docker-elk_elk
    command: >
      sh -c "
      watchmedo auto-restart \
      --directory=./djangoblog \
      --pattern='**/tasks/*.py' \
      --recursive -- \
      celery -A djangoblog worker -l info --uid=nobody --gid=nogroup
      "
    volumes:
      - type: bind
        source: ./djangoblog
        target: /app/djangoblog
    healthcheck:
      test: ["CMD-SHELL", "celery", "-A", "djangoblog", "inspect", "ping"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s

  redis:
    restart: unless-stopped
    networks:
      - default
    build:
      context: docker/redis/
    environment:
      <<: *default-env
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    # Run as privileged to allow the container to change the
    # vm.overcommit_memory setting
    privileged: true
    volumes:
      - redis:/data:rw
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'

  nginx:
    restart: on-failure
    build:
      context: docker/nginx/
    environment:
      <<: *default-env
    networks:
      - default
      - docker-elk_elk
    volumes:
      - static_volume:/app/output/static
      - ./certs:/etc/nginx/certs:ro
    develop:
      watch:
        - action: rebuild
          path: ./docker/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      timeout: 25s
      retries: 5
    ports:
      - 80:80
      - 443:443
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
    depends_on:
      app:
        condition: service_healthy

  postgres:
    restart: on-failure
    networks:
      - default
      - docker-elk_elk
    env_file:
      - .env
    environment:
      <<: *default-env
    build:
      context: ./docker/postgres
    ports:
      - 5431:5431
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${PGPORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  pgbouncer:
    image: edoburu/pgbouncer:latest
    volumes:
      - ./docker/postgres/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
    networks:
      - default
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      <<: *default-env
    depends_on:
      postgres:
        condition: service_healthy

  haproxy:
    networks:
      - default
      - docker-elk_elk
    build:
      context: docker/haproxy/
    volumes:
     - ./certs:/usr/local/etc/haproxy/certs:ro
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./docker/haproxy/haproxy.cfg
    environment:
      <<: *default-env
      HAPROXY_PORT: 8080
    ports:
      - 8080:8080
      - 8404:8404 # Haproxy stats
      - 8405:8405 # Prometheus metrics
    depends_on:
      app:
        condition: service_healthy


networks:
  default:
    driver: bridge
  # External elk docker network
  # docker network create docker-elk_elk
  docker-elk_elk:
    external: true

volumes:
  data:
  redis:
  static_volume:
