services:
  app:
    networks:
      - default
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - DEBUGPY_PROCESS_SPAWN_TIMEOUT=90
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:80 --noreload
    ports:
      - 8001:8001
      - 5678:5678
    expose:
      - 80
