services:

  # Docker logs monitoring
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8889:8889

  rabbitmq:
    image: rabbitmq:3.11.26-management
    container_name: dj-rabbitmq
    security_opt:
      - no-new-privileges:true
    ports:
      - 5675:5675
