workers = 3
threads = 2
worker_class = "gevent"
timeout = 60
loglevel = "info"
proxy_protocol = True
forwarded_allow_ips = "*"
# certfile = "certs/cert.crt"
# keyfile = "certs/cert.key"
# accesslog = "/path/to/gunicorn.access.log"
# errorlog = "/path/to/gunicorn.error.log"
