[tool.poetry]
name = "Blog application"
version = "0.1.0"
description = "Django blog"
authors = ["Viktor Sokolov <viktorsokolov.and@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10.14"
django = "^5.0.2"
djangorestframework = "^3.14.0"
requests = "^2.31.0"
drf-spectacular = "0.20.2"
psycopg2 = "^2.9.9"
django-environ = "^0.10.0"
django-extensions = "^3.2.3"
django-ckeditor = "^6.7.1"
Pillow = "^10.2.0"
django-jazzmin = "^2.6.0"
django-tagify2 = "^1.0.19"
djangorestframework-simplejwt = "^5.3.1"
django-compressor = "^4.4"
django-cors-headers = "^4.3.1"
celery = "^5.3.6"
python-logstash = "^0.4.8"
django-redis = "^5.4.0"
gunicorn = "^21.2.0"
django-compression-middleware = "^0.5.0"
dependency-injector = "^4.41.0"
django-dbbackup = "^4.1.0"
django-csp = "^3.7"
drf-writable-nested = "^0.7.0"
elasticsearch-dsl = "7.4.1"
django-silk = "^5.1.0"
sentry-sdk = "^1.40.3"
django-test-autocomplete = "^0.1.4"
ecs-logging = "^2.1.0"
django-sslserver = "^0.22"
rich = "^13.7.1"

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^4.3.0"
coverage = "^7.4.1"
Faker = "^23.1.0"
prospector = "^1.10.3"
pdbpp = "^0.10.3"
watchdog = "^4.0.0"
uvicorn = "^0.21.1"
locust = "^2.22.0"
django-watchman = "^1.3.0"
django-stubs = "^4.2.7"
djangorestframework-stubs = "^3.14.5"
openapi-spec-validator = "^0.7.1"
pre-commit = "^3.6.0"
mypy = "^1.8.0"
ruff = "^0.1.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pycln]
all = true

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
check_untyped_defs = true
warn_return_any = true
follow_imports = "skip"
exclude = ["djangoblog/tests/*", "migrations"]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "migrations"
]

# Same as Black.
line-length = 88
indent-width = 4

target-version = "py311"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E", "F", "E4", "E7", "E9", "B", "I", "DJ"]
fixable = ["ALL"]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"


plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]

[tool.django-stubs]
django_settings_module="djangoblog.settings"
strict_settings = true
