[tool.poetry]
name = "django-rest-api"
version = "0.1.0"
description = ""
authors = ["Viktor Sokolov <viktorsokolov.and@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.7"
djangorestframework = "^3.12.4"
requests = "^2.26.0"
drf-spectacular = "0.20.2"
psycopg2 = "^2.9.2"
django-environ = "^0.8.1"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pylint = "^2.11.1"
pylint-django = "^2.4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
