[tool.poetry]
name = "django-rest-api"
version = "0.1.0"
description = ""
authors = ["Viktor Sokolov <viktorsokolov.and@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0.4"
djangorestframework = "^3.12.4"
requests = "^2.26.0"
drf-spectacular = "0.20.2"
psycopg2 = "^2.9.2"
django-environ = "^0.8.1"
openapi-spec-validator = "^0.4.0"
django-stubs = "^1.10.1"
mypy = "^0.942"
rich = "^12.2.0"
django-extensions = "^3.1.5"
django-ckeditor = "^6.3.2"
Pillow = "^9.1.0"
django-jazzmin = "^2.5.0"
django-tagify2 = "^1.0.19"
djangorestframework-simplejwt = "^5.1.0"
django-compressor = "^4.0"
django-cors-headers = "^3.11.0"
pylint = "^2.13.9"
celery = "^5.2.6"
watchdog = "^2.1.8"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
django-debug-toolbar = "^3.2.4"
coverage = "^6.3.2"
Faker = "^13.3.5"
prospector = "^1.7.7"
pdbpp = "^0.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
