[tool.poetry]
name = "django-rest-api"
version = "0.1.0"
description = "Django blog"
authors = ["Viktor Sokolov <viktorsokolov.and@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.7"
djangorestframework = "^3.14.0"
requests = "^2.28.2"
drf-spectacular = "0.20.2"
psycopg2 = "^2.9.5"
django-environ = "^0.10.0"
openapi-spec-validator = "^0.5.6"
django-stubs = "^1.16.0"
django-extensions = "^3.2.1"
django-ckeditor = "^6.5.1"
Pillow = "^9.4.0"
django-jazzmin = "^2.6.0"
django-tagify2 = "^1.0.19"
djangorestframework-simplejwt = "^5.2.2"
django-compressor = "^4.3.1"
django-cors-headers = "^3.14.0"
celery = "^5.2.7"
python-logstash = "^0.4.8"
django-redis = "^5.2.0"
gunicorn = "^20.1.0"
django-compression-middleware = "^0.5.0"
dependency-injector = "^4.41.0"
django-dbbackup = "^4.0.2"
djangorestframework-stubs = "^1.10.0"
django-csp = "^3.7"
drf-writable-nested = "^0.7.0"
elasticsearch-dsl = "7.4.1"
django-silk = "^5.0.3"
sentry-sdk = "^1.22.2"

[tool.poetry.dev-dependencies]
black = "^23.1.0"
django-debug-toolbar = "^3.8.1"
coverage = "^7.2.2"
Faker = "^18.3.1"
prospector = "^1.9.0"
pdbpp = "^0.10.3"
watchdog = "^3.0.0"
uvicorn = "^0.21.1"
locust = "^2.15.1"

[tool.poetry.group.dev.dependencies]
flake8-tidy-imports = "^4.8.0"
django-watchman = "^1.3.0"
django-stubs = "^1.15.0"
djangorestframework-stubs = "^1.9.1"
rich = "^13.3.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
