[tool.poetry]
name = "django-rest-api"
version = "0.1.0"
description = ""
authors = ["Viktor Sokolov <viktorsokolov.and@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.4"
djangorestframework = "^3.12.4"
requests = "^2.26.0"
drf-spectacular = "0.20.2"
psycopg2 = "^2.9.2"
django-environ = "^0.8.1"
openapi-spec-validator = "^0.4.0"
django-stubs = "^1.10.1"
django-extensions = "^3.1.5"
django-ckeditor = "^6.3.2"
Pillow = "^9.1.0"
django-jazzmin = "^2.5.0"
django-tagify2 = "^1.0.19"
djangorestframework-simplejwt = "^5.1.0"
django-compressor = "^4.0"
django-cors-headers = "^3.11.0"
celery = "^5.2.7"
python-logstash = "^0.4.8"
django-redis = "^5.2.0"
gunicorn = "^20.1.0"
django-compression-middleware = "^0.4.1"
dependency-injector = "^4.39.1"
django-dbbackup = "^4.0.1"
djangorestframework-stubs = "^1.7.0"
elasticsearch = "^8.5.3"
django-elasticsearch-dsl = "^7.2.2"
django-csp = "^3.7"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
django-debug-toolbar = "^3.2.4"
coverage = "^6.3.2"
Faker = "^13.3.5"
prospector = "^1.7.7"
pdbpp = "^0.10.3"
rich = "^12.4.4"
watchdog = "^2.1.9"
uvicorn = "^0.18.1"
locust = "^2.9.0"

[tool.poetry.group.dev.dependencies]
flake8-tidy-imports = "^4.8.0"
django-watchman = "^1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
