[tool.poetry]
name = "Blog application"
version = "0.1.0"
description = "Django blog"
authors = ["Viktor Sokolov <viktorsokolov.and@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.7"
djangorestframework = "^3.14.0"
requests = "^2.28.2"
drf-spectacular = "0.20.2"
psycopg2 = "^2.9.5"
django-environ = "^0.10.0"
django-extensions = "^3.2.1"
django-ckeditor = "^6.5.1"
Pillow = "^9.4.0"
django-jazzmin = "^2.6.0"
django-tagify2 = "^1.0.19"
djangorestframework-simplejwt = "^5.2.2"
django-compressor = "^4.3.1"
django-cors-headers = "^3.14.0"
celery = "^5.2.7"
python-logstash = "^0.4.8"
django-redis = "^5.2.0"
gunicorn = "^20.1.0"
django-compression-middleware = "^0.5.0"
dependency-injector = "^4.41.0"
django-dbbackup = "^4.0.2"
django-csp = "^3.7"
drf-writable-nested = "^0.7.0"
elasticsearch-dsl = "7.4.1"
django-silk = "^5.0.3"
sentry-sdk = "^1.22.2"
django-test-autocomplete = "^0.1.4"
ecs-logging = "^2.1.0"
django-sslserver = "^0.22"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
django-debug-toolbar = "^3.8.1"
coverage = "^7.2.2"
Faker = "^18.3.1"
prospector = "^1.9.0"
pdbpp = "^0.10.3"
watchdog = "^3.0.0"
uvicorn = "^0.21.1"
locust = "^2.15.1"
flake8-tidy-imports = "^4.8.0"
django-watchman = "^1.3.0"
rich = "^13.3.5"
django-stubs = "^4.2.6"
djangorestframework-stubs = "^3.14.4"
openapi-spec-validator = "^0.7.1"
pre-commit = "^3.5.0"
mypy = "^1.6.1"
ruff = "^0.1.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pycln]
all = true

[tool.flake8]
max-complexity = 10

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
check_untyped_defs = true
warn_return_any = true
follow_imports = "skip"

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.8
target-version = "py3.11.6"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E", "F", "E4", "E7", "E9", "B", "I"]
fixable = ["ALL"]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"


plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]

[tool.django-stubs]
django_settings_module="djangoblog.settings"
strict_settings = true
