database: &database
  ENGINE: django.db.backends.postgresql
  NAME: blog
  USER: user
  PASSWORD: securepassword
  PORT: 5431
  HOST: postgres

storage: &static_storage
  STATIC_STORAGE:
    BACKEND: django.contrib.staticfiles.storage.StaticFilesStorage

bucket: &bucket
  GS_BUCKET_NAME: django-cdn
  GS_PROJECT_ID: django-app-431708
  GS_QUERYSTRING_AUTH: False
  USE_GC_LOCAL: False # Use GC bucket locally

default: &default
  REDIS_URL: redis://redis:6379/0
  SENTRY_ENABLED: False

local:
  <<: [*default, *static_storage]
  APP_ENV: local
  DEBUG: True
  SECRET_KEY: '@format {env[SECRET_KEY]}'
  ALLOWED_HOSTS: ['*']
  USE_GC_LOCAL: True

  # Celery
  CELERY_RESULT_BACKEND: redis://redis:6379
  CELERY_BROKER_URL: redis://redis:6379
  CELERY_TASK_ALWAYS_EAGER: False
  CELERY_TASK_EAGER_PROPAGATES: False

  CACHE_BACKEND: django_redis.cache.RedisCache

  # Database
  DATABASES:
    default:
      <<: *database

test:
  <<: *static_storage
  APP_ENV: test
  DEBUG: True
  SECRET_KEY: '@format {env[SECRET_KEY]}'
  USE_GC_LOCAL: False
  COMPRESS_OFFLINE: False
  ALLOWED_HOSTS:
    - '.testserver'
    - testserver
    - localhost

  # Celery
  CELERY_RESULT_BACKEND: 'cache+memory://'
  CELERY_BROKER_URL: 'memory://localhost/'
  CELERY_TASK_ALWAYS_EAGER: True
  CELERY_TASK_EAGER_PROPAGATES: True

  CACHES:
    default:
      'BACKEND': 'django.core.cache.backends.dummy.DummyCache'

  # Database
  DATABASES:
    default:
      <<: *database

production:
  <<: [*default, *bucket]
  APP_ENV: production
  DEBUG: False
  # SENTRY_DSN: '@format {env[SENTRY_DSN]}'
  # SECRET_KEY: '@format {env[SECRET_KEY]}'
  SECRET_KEY: MM5EZ0rZdrsc-TX9vU432Cg-L-lqpjDZ50AICyU9iDBOEOo3BNzl1uxd-Sd9Avrs0u_-Nw
  ALLOWED_HOSTS: ['*']

  STATIC_STORAGE:
    BACKEND: djangoblog.storage.CachedGCloudStorage
    OPTIONS:
      bucket_name: django-cdn
      project_id: django-app-431708
      querystring_auth: False

  COMPRESS_OFFLINE: True
  COMPRESS_OFFLINE_MANIFEST_STORAGE: djangoblog.storage.CustomOfflineManifestStorage
  COMPRESS_STORAGE: djangoblog.storage.CachedGCloudStorage
  COMPRESS_URL: https://storage.googleapis.com/django-cdn/
  STATIC_URL: https://storage.googleapis.com/django-cdn/

  # Database
  DATABASES:
    default:
      <<: *database

  # Celery
  CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
  CELERY_BROKER_URL: 'redis://redis:6379/0'
  CELERY_TASK_ALWAYS_EAGER: False
  CELERY_TASK_EAGER_PROPAGATES: False

  # Redis
  REDIS_URL: redis://redis:6379/0
  CACHE_BACKEND: django_redis.cache.RedisCache
