database: &database
  ENGINE: django.db.backends.postgresql
  NAME: blog
  USER: user
  PASSWORD: securepassword
  PORT: 5431
  HOST: localhost

bucket: &bucket
  GS_BUCKET_NAME: django-cdn
  GS_PROJECT_ID: django-app-431708
  GS_QUERYSTRING_AUTH: False
  USE_GC_LOCAL: False # Use GC bucket locally

default: &default
  REDIS_URL: redis://dj-redis:6379/0
  SENTRY_ENABLED: False

local:
  <<: *default
  APP_ENV: local
  DEBUG: True
  SECRET_KEY: '@format {env[SECRET_KEY]}'
  ALLOWED_HOSTS: ['*']
  USE_GC_LOCAL: True
  STATIC_FILES_STORAGE: django.contrib.staticfiles.storage.ManifestStaticFilesStorage
  STATIC_OPTIONS: {}
  # Celery
  CELERY_RESULT_BACKEND: redis://localhost:6379
  CELERY_BROKER_URL: redis://localhost:6379
  CELERY_TASK_ALWAYS_EAGER: False
  CELERY_TASK_EAGER_PROPAGATES: False

  # Database
  DATABASES:
    default:
      <<: *database

test:
  APP_ENV: test
  DEBUG: True
  SECRET_KEY: '@format {env[SECRET_KEY]}'
  ALLOWED_HOSTS:
    - '.testserver'
    - testserver
    - localhost

  # Celery
  CELERY_RESULT_BACKEND: 'cache+memory://'
  CELERY_BROKER_URL: 'memory://localhost/'
  CELERY_TASK_ALWAYS_EAGER: True
  CELERY_TASK_EAGER_PROPAGATES: True

  CACHES:
    default:
      'BACKEND': 'django.core.cache.backends.dummy.DummyCache'

  # Database
  DATABASES:
    default:
      <<: *database

production:
  <<: [*default, *bucket]
  APP_ENV: production
  DEBUG: True
  # SENTRY_DSN: '@format {env[SENTRY_DSN]}'
  # SECRET_KEY: '@format {env[SECRET_KEY]}'
  SECRET_KEY: MM5EZ0rZdrsc-TX9vU432Cg-L-lqpjDZ50AICyU9iDBOEOo3BNzl1uxd-Sd9Avrs0u_-Nw
  ALLOWED_HOSTS: ['*']

  STATIC_FILES_STORAGE: &static_storage djangoblog.storage.CachedStorage

  COMPRESS_OFFLINE: False
  COMPRESS_OFFLINE_MANIFEST_STORAGE: *static_storage
  COMPRESS_STORAGE: *static_storage
  COMPRESS_URL: https://storage.googleapis.com/django-cdn/
  STATIC_URL: https://storage.googleapis.com/django-cdn/
  COMPRESS_OFFLINE_MANIFEST_STORAGE_ALIAS: staticfiles

  # Database
  DATABASES:
    default:
      <<: *database
      HOST: dj-postgres

  REDIS_URL: redis://dj-redis:6379/0

  # Celery
  CELERY_RESULT_BACKEND: 'redis://dj-redis:6379/0'
  CELERY_BROKER_URL: 'redis://dj-redis:6379/0'
  CELERY_TASK_ALWAYS_EAGER: False
  CELERY_TASK_EAGER_PROPAGATES: False
