apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        io.kompose.service: djdata
    name: postgres-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
