apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app/output/static/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
