apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
spec:
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.app }}
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
              readOnly: true
            - name: static-storage
              mountPath: /app/output/static/
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: nginx-custom.conf
                path: nginx-custom.conf # Subdirectory under /etc/nginx/custom/
        - name: log
          emptyDir: {}

        - name: static-storage
          persistentVolumeClaim:
            claimName: static-storage-pvc
