apiVersion: batch/v1
kind: Job
metadata:
  name: django-static-job
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: django-static
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command: ['/bin/sh', '-c']
          args:
            - python manage.py collectstatic --noinput
          # env:
          #   - name: GOOGLE_APPLICATION_CREDENTIALS
          #     value: /secrets/key.json
          envFrom:
            - secretRef:
                name: "{{ .Values.appsecrets }}"
          volumeMounts:
            # - name: google-credentials-volume
            #   mountPath: /secrets
            #   readOnly: true
            - name: static-storage
              mountPath: /app/output/static/
      volumes:
        # - name: google-credentials-volume
        #   secret:
        #     secretName: google-credentials
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-storage-pvc
      restartPolicy: Never
  backoffLimit: 1
