name: Install Python dependencies
description: Set up dependencies for Python

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.12.5
        cache: 'pip'

    - name: Install uv
      shell: sh
      run: |
        pip install uv==0.4.5

    - name: Cache the virtualenv
      uses: actions/cache@v4.0.2
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/uv.lock') }}

    - name: Install dependencies
      shell: sh
      run: |
        uv sync --no-install-project --extra dev --frozen
