name: Install Python dependencies
description: Set up dependencies for Python

runs:
  using: composite
  steps:
    - name: Get Python version from .python-version file
      id: python_version
      run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      shell: bash

    - uses: actions/setup-python@5.6.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@a02a550bdd3185dba2ebb6aa98d77047ce54ad21 # v6.2.1
      with:
        enable-cache: true
        cache-dependency-glob: 'uv.lock'

    - name: Install dependencies
      shell: sh
      run: |
        make install-dev
