apiVersion: v1
kind: Pod
metadata:
  name: celery-worker
spec:
    # volumes:
    #   - name: google-credentials-volume
    #     secret:
    #       secretName: google-credentials
    containers:
        - args:
              - sh
              - -c
              - DJANGO_ENV=production uv run celery -A djangoblog worker -l info --uid=nobody --gid=nogroup
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
              - secretRef:
                  name: "{{ .Values.appsecrets }}"
              - configMapRef:
                  name: postgres-env
          # env:
          #   - name: GOOGLE_APPLICATION_CREDENTIALS
          #     value: /secrets/key.json

          # volumeMounts:
          #   - name: google-credentials-volume
          #     mountPath: /secrets
          #     readOnly: true
          livenessProbe:
              exec:
                  command:
                      - celery
                      - -A
                      - djangoblog
                      - inspect
                      - ping
              failureThreshold: 5
              periodSeconds: 15
              timeoutSeconds: 15
              initialDelaySeconds: 25
          name: celery-worker
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     cpu: '2'
          #     memory: '2Gi'
    restartPolicy: OnFailure
