services:
  application:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        DEV_DEPS: true
    env_file:
      - ../.env
    environment:
      DJANGO_LOG_LEVEL: DEBUG
      DJANGO_ENV: production
      TZ: Europe/Riga
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
    depends_on:
      redis-master:
        condition: service_healthy
      redis-sentinel:
        condition: service_healthy
      postgres:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
