services:
  application:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        DEV_DEPS: true
    env_file:
      - ../.env
    environment:
      DJANGO_LOG_LEVEL: DEBUG
      DJANGO_ENV: development
      TZ: Europe/Riga
    cap_add:
      - SYS_PTRACE
    depends_on:
      redis-master:
        condition: service_healthy
      redis-sentinel:
        condition: service_healthy
      postgres:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
