{{ - if .Values.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  labels:
    io.kompose.service: app
    track: canary
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: app-canary
spec:
  replicas: {{ .Values.canary.replicas | default 1 }}
  selector:
    matchLabels:
      io.kompose.service: app
      track: canary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 2
  template:
    metadata:
      labels:
        io.kompose.service: app
        track: canary
    spec:
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: django
          image: '{{ .Values.canary.image.repository | default .Values.image.repository }}:{{ .Values.canary.image.tag }}'
          imagePullPolicy: {{ .Values.canary.image.pullPolicy | default .Values.image.pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: '{{ .Values.appsecrets }}'
            - configMapRef:
                name: postgres-env
          volumeMounts:
            - name: static-storage
              mountPath: /app/output/static/
      volumes:
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-storage-pvc
{{ - end }}
