{{ - if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django
  namespace: production
  labels:
    release: prometheus
    app: django
spec:
  selector:
    matchLabels:
      io.kompose.service: app
      track: stable
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http
{{ - end }}
