name: Install Python dependencies

steps:
  - uses: actions/checkout@v4.1.7

  - name: Setup Python
    uses: actions/setup-python@v5.1.0
    with:
      python-version: 3.10.14
      cache: 'pip'

  - name: Install poetry
    run: |
      pip install poetry==1.8.3

  - name: Cache the virtualenv
    uses: actions/cache@v4
    with:
      path: ./.venv
      key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

  - name: Install dependencies
    run: |
      poetry install --no-interaction
