apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env
  labels:
    app: postgres
data:
  DEBUG: 'False'
  PGPORT: '5431'
  POSTGRES_DB: blog
  POSTGRES_HOST: postgres
  POSTGRES_MAX_CONNECTIONS: '200'
  POSTGRES_PASSWORD: securepassword
  POSTGRES_USER: user
  POSTGRES_VERSION: '16.4'
  TZ: Europe/Riga
