apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: postgres
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: postgres
spec:
  ports:
    - protocol: TCP
      port: 5431
      targetPort: 5431
  selector:
    io.kompose.service: postgres
