apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o infra/k8s
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  volumes:
    - name: google-credentials-volume
      secret:
        secretName: google-credentials
  containers:
    - args:
        - sh
        - -c
        - DJANGO_ENV=production celery -A djangoblog worker -l info --uid=nobody --gid=nogroup
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/key.json
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              key: DEBUG
              name: env-prod
        - name: DJANGO_ENV
          valueFrom:
            configMapKeyRef:
              key: DJANGO_ENV
              name: env-prod
        - name: GS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              key: GS_BUCKET_NAME
              name: env-prod
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: SECRET_KEY
              name: env-prod
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              key: SENTRY_DSN
              name: env-prod
      image: victorysokolov/django-blog:4012f10461efae7d0927126fb69928279d3f892b
      volumeMounts:
        - name: google-credentials-volume
          mountPath: /secrets
          readOnly: true
      livenessProbe:
        exec:
          command:
            - celery
            - -A
            - djangoblog
            - inspect
            - ping
        failureThreshold: 5
        periodSeconds: 15
        timeoutSeconds: 10
      name: dj-celery-worker
      imagePullPolicy: Always
      # resources:
      #   limits:
      #     cpu: '2'
      #     memory: '2Gi'
  restartPolicy: OnFailure
