apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o infra/k8s
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: dj-app
  name: dj-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80 # External port
      targetPort: 80 # Django internal port
  selector:
    io.kompose.service: dj-app
