templates:
  default: &default
    namespace: default
    wait: true

releases:
  - name: configmap
    <<: *default
    chart: ./charts/configmap

  - name: debugpy
    <<: *default
    chart: ./charts/debugpy
    values:
      - values.yaml

  - name: celery
    <<: *default
    chart: ./charts/celery
    values:
      - values.yaml
    needs:
      - redis
      - postgres

  - name: haproxy
    <<: *default
    chart: ./charts/haproxy
    values:
      - ./charts/haproxy/values.yaml

  - name: nginx
    <<: *default
    chart: ./charts/nginx
    values:
      - ./charts/nginx/values.yaml

  - name: redis
    chart: ./charts/redis
    <<: *default
    values:
      - ./charts/redis/values.yaml
    needs:
      - configmap

  - name: django
    <<: *default
    chart: ./charts/django
    values:
      - values.yaml
    needs:
      - postgres
      - redis

  - name: postgres
    <<: *default
    chart: ./charts/postgres
    values:
      - ./charts/postgres/values.yaml
    needs:
      - configmap

  - name: static-files
    <<: *default
    chart: ./charts/static-files
    values:
      - values.yaml
