apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o infra/k8s
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  containers:
    - env:
        - name: MASTER
          value: 'true'
        - name: TZ
          value: Etc/GMT-3
      image: redis
      livenessProbe:
        exec:
          command:
            - redis-cli
            - --raw
            - incr
            - ping
      name: dj-redis
      ports:
        - containerPort: 6379
          protocol: TCP
      # resources:
      #   limits:
      #     cpu: '1'
      #     memory: '512Mi'
      securityContext:
        readOnlyRootFilesystem: false
      volumeMounts:
        - mountPath: /usr/local/etc/redis/data
          readOnly: false
          name: redis-cm0
        - mountPath: /usr/local/etc/redis/redis.conf
          name: redis-cm1
          subPath: redis.conf
  restartPolicy: OnFailure
  volumes:
    - name: redis-data
      emptyDir: {}
    - configMap:
        name: redis-cm0
      name: redis-cm0
    - configMap:
        items:
          - key: redis.conf
            path: redis.conf
        name: redis-cm1
      name: redis-cm1
