apiVersion: v1
kind: Namespace
metadata:
  name: workload-identity
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: django-service-account@django-app-431708.iam.gserviceaccount.com
  name: workload-identity-user
  namespace: workload-identity
