apiVersion: batch/v1
kind: Job
metadata:
  name: django-static-job
  namespace: production
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: django-static
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command: ['/bin/sh', '-c']
          args:
            - python manage.py collectstatic --noinput && python manage.py compress --force
          envFrom:
            - secretRef:
                name: "{{ .Values.appsecrets }}"
          volumeMounts:
            - name: static-storage
              mountPath: /app/output/static/
      volumes:
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-storage-pvc
      restartPolicy: Never
  backoffLimit: 1
