apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.temp.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: haproxy
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.temp.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: haproxy
    spec:
      restartPolicy: Always
      containers:
        - image: 'haproxy:{{ .Values.image_tag}}'
          name: haproxy
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: haproxy-config-volume
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: haproxy-config-volume
          configMap:
            name: haproxy-configmap
