apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: {{ .Values.app }}
  labels:
    io.kompose.service: {{ .Values.app }}
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.app }}
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.app }}
    spec:
      restartPolicy: Always
      containers:
        - image: 'haproxy:{{ .Values.image_tag }}'
          name: {{ .Values.app }}
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: haproxy-config-volume
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: haproxy-config-volume
          configMap:
            name: haproxy-configmap
