apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.temp.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: haproxy
  name: haproxy
spec:
  type: LoadBalancer
  ports:
    - name: 'http'
      port: 8080
      targetPort: 8080
      nodePort: 30003 # External port accessible through localhost
  externalIPs:
    # minikube IP
    - 192.168.64.2
  selector:
    io.kompose.service: haproxy
