global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scheme: http
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    scheme: http
    scrape_interval: 1m
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['app:80']

  - job_name: 'haproxy-metrics'
    scheme: http
    static_configs:
      - targets: ['haproxy:8405']
    params:
      scope:
        - frontend
        - backend
        - server

  - job_name: gunicorn
    scheme: http
    static_configs:
      - targets: ['statsd-exporter:9102']
