global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app'
    scrape_interval: 5s
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['app:80']

  - job_name: 'haproxy-metrics'
    static_configs:
      - targets: ['haproxy:8405']
    params:
      scope:
        - frontend
        - backend
