global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - follow_redirects: true
      scheme: http
      enable_http2: true
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: [alertmanager:9093]

scrape_configs:
  - job_name: 'prometheus'
    scheme: http
    honor_timestamps: true
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'kube-metrics'
    scheme: http
    static_configs:
      # Will not work on Linux
      - targets: ['host.docker.internal:8085']

  - job_name: 'app'
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['app:80']

  - job_name: 'haproxy-metrics'
    scheme: http
    static_configs:
      - targets: ['haproxy:8405']
    params:
      scope:
        - frontend
        - backend
        - server

  - job_name: gunicorn
    scheme: http
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: postgres-exporter
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: celery-exporter
    scheme: http
    static_configs:
      - targets: ['celery-exporter:9808']

  - job_name: pgbouncer-exporter
    scheme: http
    static_configs:
      - targets: ['pgbouncer-exporter:9127']

  - job_name: nginx-exporter
    scheme: http
    static_configs:
      - targets: ['nginx-exporter:9113']
