groups:
  - name: Instance Down
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: 'Instance {{ $labels.instance }} down'
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes'

      - alert: Haproxy response time
        expr: |
          avg by(proxy) (
            haproxy_backend_response_time_average_seconds{proxy="server_backend"} offset 1m
          ) > 3
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'Haproxy response time degraded'
          description: 'Haproxy {{ $labels.instance }} of job {{ $labels.job }} has been degraded'
