groups:
  - name: Instance Down
    rules:
      - alert: InstanceDown
        expr: up{job!="kube-metrics"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: 'Instance {{ $labels.instance }} down'
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes'

  - name: PgBouncer
    rules:
      - alert: PgBouncerHighClientWaitTime
        expr: |
          max by (database) (
            pgbouncer_pools_client_maxwait_seconds{database!="pgbouncer"} > 2
          )
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'High client wait time for {{ $labels.database }}'
          description: |
            PgBouncer client wait time is {{ $value }}s for database {{ $labels.database }}
            (threshold: 2s)

  - name: Haproxy
    rules:
      - alert: HaproxyResponseTime
        expr: |
          avg by(proxy) (
            haproxy_backend_response_time_average_seconds{proxy="server_backend"}
          ) > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: 'High response time for {{ $labels.proxy }}'
          description: 'Average response time for {{ $labels.proxy }} is {{ $value }}s (threshold: 10s)'
