{
 "title": "Django App Dashboard",
 "description": "Djago App Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Prometheus", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "rate",
    "label": "Rate",
    "query": "30s : 30s,1m : 1m,10m : 10m,15m : 15m,30m : 30m,1h : 1h,6h : 6h,12h : 12h"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "haproxy:8405 : haproxy:8405,app:80 : app:80"
   }
  ]
 },
 "panels": [
  { "title": "Haproxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frontend Sessions",
   "type": "timeseries",
   "description": "Haproxy Frontend Sessions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n    haproxy_frontend_current_sessions{job=~\"$job\", proxy=\"http-in\", instance=~\"$instance\"}\n) or vector(0)\n",
     "legendFormat": "Total sessions by (frontend)\n"
    }
   ]
  },
  {
   "title": "Backend Sessions",
   "type": "timeseries",
   "description": "Haproxy Backend Sessions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(haproxy_backend_current_sessions{job=~\"$job\", instance=~\"$instance\"}) or vector(0)\n",
     "legendFormat": "Total sessions by (backend)\n"
    }
   ]
  },
  {
   "title": "Frontend Session Limit",
   "type": "timeseries",
   "description": "Frontend Session Limit",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(\n    haproxy_frontend_limit_sessions{job=~\"$job\", proxy=\"http-in\", instance=~\"$instance\"}\n) or vector(0)\n",
     "legendFormat": "Frontned Session Limit\n"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "Haproxy FAverage Response Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(\n haproxy_backend_response_time_average_seconds{job=~\"$job\", instance=~\"$instance\"}\n) or vector(0)\n",
     "legendFormat": "Haproxy average response time\n"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "description": "Haproxy Status Codes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(\n    rate(haproxy_frontend_http_responses_total{\n        job=~\"$job\",\n        proxy=\"http-in\",\n        instance=~\"$instance\"\n    }[$__rate_interval])\n) by (code) or vector(0)\n",
     "legendFormat": "Haproxy status codes\n"
    }
   ]
  },
  { "title": "Django", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "DB Query Errors",
   "type": "gauge",
   "description": "Django DB Query Errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(\n    max_over_time(\n        django_db_errors_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]\n    )\n)\n",
     "legendFormat": "Django ORM DB errors count\n"
    }
   ]
  },
  {
   "title": "DB Connection Errors",
   "type": "gauge",
   "description": "Django Database Connection Errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(\n    max_over_time(\n        django_db_new_connection_errors_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]\n    )\n)\n",
     "legendFormat": "Django ORM DB errors count\n"
    }
   ]
  },
  {
   "title": "Django Request Latency",
   "type": "timeseries",
   "description": "Django Request Latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.50,\n    sum(irate(\n        django_http_requests_latency_seconds_by_view_method_bucket{\n            job=~\"$job\", instance=~\"$instance\"\n        }[$__rate_interval]\n    )) by (le)\n) or vector(0)\n",
     "legendFormat": "Django Request latency\n"
    }
   ]
  },
  {
   "title": "DB Total Queries",
   "type": "timeseries",
   "description": "Django Database Total Queries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(\n    irate(django_db_execute_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n) by (vendor) or vector(0)\n",
     "legendFormat": "Database Total Queries\n"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "description": "Cache Hit Ratio",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(\n    django_cache_get_hits_total{\n        job=~\"$job\", instance=~\"$instance\"\n    }) by (backend) / sum(django_cache_get_total{\n        job=~\"$job\", instance=~\"$instance\"\n    }) by (backend)\n",
     "legendFormat": "Cache Hit Ratio\n"
    }
   ]
  }
 ]
}