apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-debug"
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: victorysokolov/django-blog:cf825f65ee3b119b77a3c45992ced5daba20caa0
          command:
            [
              'sh',
              '-c',
              'pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload',
            ]
          tty: true
          stdin: true
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
          ports:
            - containerPort: 80 # Django app port
            - containerPort: 5678 # Debugpy port
          envFrom:
            - secretRef:
                name: {{ .Values.appsecrets }}
          env:
            - name: DEV_DEPS
              value: 'true' # Install development dependencies
      restartPolicy: Always
