apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.appName }}-debug'
  namespace: production
  labels:
    app: '{{ .Values.appName }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '{{ .Values.appName }}'
  template:
    metadata:
      labels:
        app: '{{ .Values.appName }}'
    spec:
      containers:
        - name: '{{ .Values.appName }}'
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          command:
            [
              'sh',
              '-c',
              'pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload',
            ]
          tty: true
          stdin: true
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
          ports:
            - containerPort: 80 # Django app port
            - containerPort: 5678 # Debugpy port
          envFrom:
            - secretRef:
                name: "{{ .Values.appsecrets }}"
            - configMapRef:
                name: postgres-env
          env:
            - name: DEV_DEPS
              value: 'true' # Install development dependencies
      restartPolicy: Always
