apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app }}
    spec:
      containers:
        - name: pgbouncer
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app }}
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app }}
                  key: POSTGRESQL_PASSWORD
            - name: PGBOUNCER_AUTH_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app }}
                  key: PGBOUNCER_AUTH_USER_PASSWORD
          ports:
            - containerPort: 6432
            - containerPort: 9127

          # Metrics exporter sidecar
        - name: pgbouncer-exporter
          image: prometheuscommunity/pgbouncer-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9127
              name: metrics
          env:
            - name: DATA_SOURCE_NAME
              value: "postgres://{{ .Values.metrics.user | default "pgbouncer" }}:{{ .Values.metrics.password | default "" }}@localhost:6432/pgbouncer?sslmode=disable"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

          volumeMounts:
            - name: config
              mountPath: /etc/pgbouncer/pgbouncer.ini
              subPath: pgbouncer.ini
            - name: auth
              mountPath: /etc/pgbouncer/userlist.txt
              subPath: userlist.txt
      volumes:
        - name: config
          configMap:
            name: {{ .Values.app }}
        - name: auth
          secret:
            secretName: {{ .Values.app }}
