apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: production

spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.pgport }}
      targetPort: 6432
  selector:
    app.kubernetes.io/name: {{ .Values.app }}
