apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6432
  selector:
    app.kubernetes.io/name: {{ .Values.app }}
