{{ - if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pgbouncer
  namespace: production
  labels:
    release: prometheus
    app: pgbouncer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http
{{ - end }}
