apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  containers:
    - env:
        - name: MASTER
          value: 'true'
        - name: TZ
          value: Europe/Riga
      image: redis:{{ .Values.image_tag }}
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command:
            - redis-cli
            - --raw
            - incr
            - ping
        failureThreshold: 5
        periodSeconds: 15
        timeoutSeconds: 12
      name: redis
      ports:
        - containerPort: 6379
          protocol: TCP
      # resources:
      #   limits:
      #     cpu: '1'
      #     memory: '512Mi'
      securityContext:
        readOnlyRootFilesystem: false
      volumeMounts:
        - mountPath: /usr/local/etc/redis/data
          readOnly: false
          name: redis-cm0
        - mountPath: /usr/local/etc/redis/redis.conf
          name: redis-cm1
          subPath: redis.conf
  restartPolicy: OnFailure
  volumes:
    - name: redis-data
      emptyDir: {}
    - configMap:
        name: redis-cm0
      name: redis-cm0
    - configMap:
        items:
          - key: redis.conf
            path: redis.conf
        name: redis-cm1
      name: redis-cm1
