---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: production
  labels:
    app: redis
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  clusterIP: None # headless service to match StatefulSet serviceName
