apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  name: redis
spec:
  ports:
    - name: '6379'
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis
