# Generated by Django 3.2.7 on 2021-09-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
