# Generated by Django 3.2.7 on 2021-11-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
