# Generated by Django 3.2.9 on 2022-04-08 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djangoblog", "0002_auto_20220408_1729"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
    ]
