# Generated by Django 3.2.9 on 2021-11-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0002_delete_posts'),
    ]

    operations = [
    ]
