# Generated by Django 3.2.9 on 2022-04-08 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djangoblog", "0003_auto_20220408_1737"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
    ]
