# Generated by Django 3.2.9 on 2022-04-09 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djangoblog", "0005_auto_20220408_1844"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
    ]
