# Generated by Django 3.2.9 on 2022-04-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0006_remove_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
