# Generated by Django 3.2.9 on 2022-04-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoblog', '0007_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
