name: ci

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.*'
      - package.json
      - yarn.lock

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: securepassword
          POSTGRES_DB: blog
        ports:
          - 5431:5431
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4.1.7
      - id: setup
        uses: ./.github/actions/install-deps

      - name: Run tests
        env:
          DB_HOST: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5431] }}
        run: |
          set -v
          make tests-ci
