name: ci

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.*'
      - package.json
      - yarn.lock

jobs:
  postgres-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7

      - name: Start PostgreSQL
        run: |
          docker run -d \
            --name postgres \
            -e POSTGRES_DB=blog \
            -e POSTGRES_USER=user \
            -e POSTGRES_PASSWORD=securepassword \
            -e DB_HOST=localhost \
            -p 5431:5431 \
            -v ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d \
            postgres:15

  test:
    runs-on: ubuntu-latest
    needs: postgres-db
    steps:
      - uses: actions/checkout@v4.1.7
      - id: setup
        uses: ./.github/actions/install-deps

      - name: Run tests
        run: |
          set -v
          make tests
