name: ci

on:
  push:
    branches: [main, master]

  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  vm-job:
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
        cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    env:
      PGPORT: 5431
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: securepassword
      POSTGRES_USER: user
      PGHOST: localhost
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    services:
      postgres:
        image: postgres:16.4
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          PGPORT: ${{ env.PGPORT}}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/install-deps

      - name: Run Django Checks
        shell: sh
        run: |
          set -v
          make run-checks

      - name: Run tests
        run: |
          set -v
          make test

