name: ci

on:
  push:
    branches: [main, master]

  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  vm-job:
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
        cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    env:
      PGPORT: 5431
      POSTGRES_DB: blog
      POSTGRES_PASSWORD: securepassword
      POSTGRES_USER: user
      PGHOST: localhost
      SECRET_KEY: yEEl2mN5lw-u2YEOW0k-jtc967R_W532mCGVYiZpwwMmcplQTGG2HIU0KbsHModx4Vgs

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          PGPORT: ${{ env.PGPORT}}
        ports:
          - 5431:5431
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/install-deps

      - name: Run Django Check
        shell: sh
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
        run: |
          export SECRET_KEY=${{ env.SECRET_KEY }}
          set -v
          make security-check

      - name: Run tests
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
        run: |
          set -v
          make test

