name: Create GitHub Tag & Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref (branch or tag)'
        required: true
        default: 'master'
  workflow_run:
    workflows: ['CI-checks']
    branches: [master]
    types: [completed]

jobs:
  create-tag:
    uses: victory-sokolov/githooks/.github/workflows/create-tag-from-version-txt.yml@main

  create-release:
    runs-on: ubuntu-latest
    name: Create GitHub Release
    needs: create-tag
    if: needs.create-tag.outputs.should_create_tag == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ needs.create-tag.outputs.tag_name || 'master' }}

      - name: Get the version
        id: vars
        run: |
          # Get the tag that was just created
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Using tag: $TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          body: |
            ## Release ${{ env.TAG }}

            Automated release created by GitHub Actions
          draft: false
          prerelease: false
          generate_release_notes: true
