name: docker

on:
    push:
        branches: [main, master]

    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@master

            - name: Lint Dockerfile using Checkov
              id: checkov
              uses: bridgecrewio/checkov-action@master
              with:
                  directory: .
                  framework: dockerfile # Only ask for Dockerfile scans
                  quiet: true # Show only failed checks
                  container_user: 1000
