name: E2E Tests
on:
    workflow_dispatch:
    workflow_call:
        inputs:
            environment:
                type: string
                required: true

env:
    SECRET_KEY: yEEl2mN5lw-u2YEOW0k-jtc967R_W532mCGVYiZpwwMmcplQTGG2HIU0KbsHModx4Vgs
    NAME: blog
    USER: user
    PASSWORD: securepassword
    PORT: 5431
    HOST: localhost

jobs:

    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - name: Set up PostgreSQL
              uses: ./.github/workflows/postgresql-setup.yml

            - uses: actions/checkout@master
            - id: setup
              uses: ./.github/actions/install-deps

            - name: Start Django server
              continue-on-error: false
              run: |
                set -v
                uv run python manage.py runserver || exit 1

            - name: Run your tests
              run: |
                set -v
                pip install playwright
                playwright install --with-deps chromium
                python e2e/test_signup.py

            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-traces
                  path: test-results/
                  retention-days: 5
