name: E2E Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
        DJANGO_ENV: local
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        POSTGRES_DB: blog
        POSTGRES_PASSWORD: securepassword
        POSTGRES_USER: user

    services:
      postgres:
        image: postgres:16.4
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5431:5431
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 8s
          --health-retries 5

    steps:
      - uses: actions/checkout@master
      - id: setup
        uses: ./.github/actions/install-deps

      - name: Run Django Checks
        shell: sh
        run: |
          set -v
          make run-checks

      - name: Apply Migrations
        env:
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            POSTGRES_DB: blog
            POSTGRES_PASSWORD: securepassword
            POSTGRES_USER: user
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5431
        run: |
            set -v
            make migrate

      - name: Start Django server
        continue-on-error: false
        run: |
          set -v
          make dev &

      - name: Install deps
        run: |
          set -v
          pip install playwright
          playwright install --with-deps chromium

      - name: Run tests
        run: |
          set -v
          python e2e/signup.py

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 5
