name: Reusable PostgreSQL Setup

on:
  workflow_call:
    inputs:
      POSTGRES_USER:
        description: 'PostgreSQL user'
        type: string
        required: false
        default: 'postgres'
      POSTGRES_PASSWORD:
        description: 'PostgreSQL password'
        required: true
        type: string
        default: 'securepassword'
      POSTGRES_DB:
        description: 'PostgreSQL database'
        required: true
        type: string
        default: 'blog'
      PGPORT:
        description: 'PostgreSQL Port'
        required: true
        type: string
        default: '5431'
      PGHOST:
        description: 'PostgreSQL Host'
        required: true
        type: string
        default: 'localhost'

jobs:
  setup-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.4
        env:
          POSTGRES_USER: ${{ inputs.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ inputs.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ inputs.POSTGRES_DB }}
        ports:
          - ${{ inputs.PGPORT }}:${{ inputs.PGPORT }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
