name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0/50 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v41.0.9
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: victory-sokolov/django-rest
        with:
          configurationFile: renovate.json
          token: ${{ github.token }}
