name: tfsec-pr-commenter
on:

  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

  push:
    branches: [master, main]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}

  terraform-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@main

      - name: terraform fmt
        run: terraform fmt -check=true

      - name: terraform validate
        run: terraform validate

      - name: Run terraform plan
        run: terraform plan
